# Generated by Django 2.2.3 on 2019-08-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlideShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='slideImages')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='slideImages')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='slideImages')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
            ],
        ),
    ]
