# Generated by Django 2.2.3 on 2019-08-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
