# Generated by Django 2.2.3 on 2019-08-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_books', '0003_fine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fine',
            options={'verbose_name_plural': 'Fine List'},
        ),
        migrations.AddField(
            model_name='fine',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
