# Generated by Django 2.2.3 on 2019-08-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_books', '0005_auto_20190822_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publications',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
