# Generated by Django 2.2.3 on 2019-08-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='fine_code',
        ),
        migrations.AddField(
            model_name='payment',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bKash_ac',
            field=models.IntegerField(max_length=11),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(max_length=15),
        ),
    ]
