# Generated by Django 2.2.3 on 2019-08-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0002_auto_20190804_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bKash_ac',
            field=models.IntegerField(),
        ),
    ]
