# Generated by Django 2.2.3 on 2019-08-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0004_auto_20190822_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
